name: Affect
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - nltk
  - scikit-learn
  - os
  - pytorch=1.12.1  # Add PyTorch to ensure compatibility with the transformers library
  - transformers=4.17.0  # This will attempt to get the latest version available on conda channels
